services:
  web:
    image: nginx:latest
    container_name: laravel-app-web
    ports:
      - "8000:80"
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  app:
    image: php:8.4-fpm
    container_name: laravel-app-app
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel-app-db
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: admin@123
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "33306:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
